### ISSUE TITLE
Does it work on Zabbix 2.2

### ISSUE THREAD

**Issue by gabricar** [alerta/zabbix-alerta#20]
I have two environments first one running Zabbix 3.0 and works fine. Second one zabbix 2.2 does not.

when I try to run the script on CLI I get:
Zabbix 3.0
[root@zabbix alertscripts]# /usr/bin/zabbix-alerta
usage: zabbix-alerta SENDTO SUMMARY BODY
zabbix-alerta: error: too few arguments

Zabbix 2.2
[root@zbx01 zabbix]# /usr/bin/zabbix-alerta
Traceback (most recent call last):
  File "/usr/bin/zabbix-alerta", line 9, in <module>
    load_entry_point('zabbix-alerta==3.4.0', 'console_scripts', 'zabbix-alerta')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/bdist.linux-x86_64/egg/zabbix_alerta.py", line 16, in <module>
ImportError: cannot import name ApiClient

Thx

**Comment by satterly** [comment]
I've made some updates to the script. Try re-installing / updating and let me know how you go.
```
$ pip install git+https://github.com/alerta/zabbix-alerta --upgrade
```

**Comment by gabricar** [comment]
@satterly Perfect!!!! I don't know how to thank you!!! 
you can close this bug.

Have a good Sunday!
